### ISSUE TITLE
Recipie for elytra

### ISSUE THREAD

**Issue by MrPetrikkov** [AShadedBlobfish/elytra-recipe#1]
Hi I didnt know how to reach out to you but, the Elytra can be repeared with Phantome mebrane. it would make a lot of sense if they were to be craft with the same material they are repared with :3 thats it. thank u for the mod uwu

**Comment by AShadedBlobfish** [comment]
Hi, I was thinking about doing this, but the mod was originally made for just my friends and I, before I decided to post it on modrinth, and so we chose what we wanted the recipe to be together. I have thought that I could make two versions; a cheaty version (how it is currently) and a more vanilla version (probably using phantom membranes along with one or two other vanilla items)

**Comment by AShadedBlobfish** [comment]
I have created a new version of the mod to include a more vanilla style recipe, also omitting the extra items, that version can be downloaded [here](https://github.com/AShadedBlobfish/elytra-recipe/releases/tag/vanilla-1.0.0). See README.md for the new recipe. Any feedback is welcome, but I am going to close this issue now as the feature has been implemented.
